# Generated by Django 4.2.3 on 2024-06-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='updated_at',
        ),
    ]
