# Generated by Django 4.2.3 on 2024-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_galleryphoto_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
