# Generated by Django 4.2.3 on 2024-06-30 16:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20240629_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Gallery photo', 'verbose_name_plural': 'Gallery photos'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings'},
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_uz',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_phone_ru',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_phone_uz',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_telegram_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_telegram_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='latitude_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='latitude_uz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='locations_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='locations_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='longitude_ru',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='longitude_uz',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram_bot_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram_bot_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='working_horse_end_ru',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='working_horse_end_uz',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='working_horse_start_ru',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='working_horse_start_uz',
            field=models.TimeField(null=True),
        ),
    ]
