# Generated by Django 4.2.3 on 2024-07-03 12:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20240629_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Gallery photo', 'verbose_name_plural': 'Gallery photos'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings'},
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
