# Generated by Django 4.2.3 on 2024-06-29 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_remove_product_content_ru_remove_product_content_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('count', models.IntegerField(default=0)),
                ('count_ru', models.IntegerField(default=0, null=True)),
                ('count_uz', models.IntegerField(default=0, null=True)),
                ('free_count', models.IntegerField(default=0)),
                ('free_count_ru', models.IntegerField(default=0, null=True)),
                ('free_count_uz', models.IntegerField(default=0, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('status_change', models.BigIntegerField()),
                ('product_price', models.BigIntegerField()),
                ('total_price', models.BigIntegerField()),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('costumer_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('costumer_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
